Feature/order
HWANGJEONGHYEON1/HanshinShop pull request #4
Opened 2021-06-09 14:01 UTC by HWANGJEONGHYEON1

2021-06-15 13:56 UTC, dave915 requested changes
😁

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/controller/order/OrderController.java
> +        log.info("dto {} ", dtoList);
interceptor 이용해서 요청, 응답 로그 찍는거 고고

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/controller/order/OrderController.java
> +    @GetMapping("/orderCount")
`/order/count`로 하면 어떰?

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/controller/order/OrderController.java
> +    @ResponseBody
페이지 리턴하는 Controller만들어서 그건 `@Controller`로 사용하고 나머지는 `@RestController` 로 하고 `/api`를 prefix로 가져가는건 어떰?

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/controller/order/OrderController.java
> +    @GetMapping("/order-details")
`/order/details`

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/controller/order/OrderController.java
> +        return new ResponseEntity<>(orderDetails, HttpStatus.OK);
ResponseEntity를 다 쓰거나 안쓰거나? 개인적으로는 나는 잘 안씀

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/controller/order/OrderController.java
> +        return new ResponseEntity<>("success", HttpStatus.OK);
`return new ResponseEntity<>("success", HttpStatus.OK);`
그냥 Void로 하고 Status Code 200 줘도 될 것 같음

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/service/OrderService.java
> +        OrderVO orderVO = orderMapper.selectOne(userId);
`VO` 와 `Entity`의 차이는 무엇일까? 🤔

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/controller/order/OrderController.java
> +            return new ResponseEntity<>("fail", HttpStatus.INTERNAL_SERVER_ERROR);
`@ControllerAdvice`하고 `@RestControllerAdivce` 한번 찾아보면 좋을 것 같음. 
주문 취소 실패하면 Service에서 그대로 Exception을 던지고 `@ControllerAdvice` or `@RestControllerAdivce` 에서 처리하도록 해봐

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/controller/order/OrderController.java
> +        final List<OrderDetailDto> orderDetails = orderService.findOrderDetails(user.getId());
`orderDetails` 가 몇개나 조회 될지 모르는데, List로 조회 하는 것 보단 Count를 조회 하는게 좋지 않을까?

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/service/OrderService.java
> +        return one;
```suggestion
        return orderMapper.selectOne(id);
```

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/service/OrderService.java
> +        final User user = userMapper.findById(userId);
그냥 Controller에서 주는 user 써도 될 것 같은데?

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/service/OrderService.java
> +        }
한번 Stream으로 바꿔볼래?

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/service/OrderService.java
> +        return order.getId();
return 하는 order id 를 사용하는곳이 없어보임

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/service/OrderService.java
> +        saveOrderGoodsItem(orderGoodsVOList, order);
```suggestion
        saveOrderGoodsItem(orderGoodsVOList, order);
        cartMapper.deleteAll(userId);
```
`saveOrderGoodsItem` 까지가 주문 저장이기 때문에 `cartMapper.deleteAll(userId);` 를 밑으로 내리는게 좋을듯

2021-06-15 13:56 UTC, dave915 commented on src/main/java/com/hanshin/shop/service/OrderService.java
> +        return orderMapper.cancel(orderVO.getId(), orderVO.getState());
`orderMapper.cancel(orderVO);` 이렇게 하고 Mapper에서 각 필드를 불러도 될 듯

2021-06-16 16:21 UTC, HWANGJEONGHYEON1 commented on src/main/java/com/hanshin/shop/service/OrderService.java
> +        OrderVO orderVO = orderMapper.selectOne(userId);
### VO
- value obejct
- 값 객체
- equals() & hashcode() 오버라이딩
- 내부에 선언된 필드 모든 값들이 vo 객체마다 다 똑같아야함
- 객체의 불변성을 보장한다.


### DTO
- data transfer object
- 주로 비동기 처리할 때 사용
- 스프링 부트에서 Jackson 라이브러리 이용하여 json 타입으로 변환해주는데 이 때 사용한다.
- 데이터 가공처리

### Entity
- DB 테이블 내에 존재하는 컬럼만을 필드로 가지는 클래스
- 상속을 받거나 구현체여서는 안된다,
- 테이블 내에 존재하지 않는 컬럼이 있으면 안된다.
- 주로 JPA

2021-06-16 16:21 UTC, HWANGJEONGHYEON1 commented on src/main/java/com/hanshin/shop/service/OrderService.java
> +        OrderVO orderVO = orderMapper.selectOne(userId);
하는김에 DTO도 좀알아봤습니다.. 흐흐

2021-06-17 09:22 UTC, merged